config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'recipes#index'
get 'pages/about'
get 'pages/users'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients, dependent: :destroy
	accepts_nested_attributes_for :ingredients, allow_destroy: true

	has_many :steps, dependent: :destroy
	accepts_nested_attributes_for :steps, allow_destroy: true

	mount_uploader :image, ImageUploader
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end

	def users
	end
	
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:remove_image, :image, :title, :description, ingredients_attributes:[:id, :content, :destroy], steps_attributes:[:id, :direction, :destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeDb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<div class="container">

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
<%= link_to "Home", root_path, class: 'navbar-brand' %>
<%= link_to "About", pages_about_path, class: 'navbar-brand' %> 

<% if user_signed_in? %>
<%= link_to current_user.email, edit_user_registration_path, class: 'navbar-brand' %>
<%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-brand' %>
<% else %>
<%= link_to "Sign Up", new_user_registration_path, class: 'navbar-brand' %>
<%= link_to "Login", new_user_session_path, class: 'navbar-brand' %>
<% end %>
</nav>



  <body>
    <%= yield %>
    <br>
    <br>
    <footer>
      <h4>Footer Info Here</h4>
    </footer>
  </body>
</div><!-- container -->

</html>

app/views/pages/about.html.erb
<div class="container">
<h1>About Page</h1>

<div class="row">
  <h2>Tina's Recipe App</h2>
  <p>Cliche iceland tousled glossier banh mi hammock. Waistcoat man braid sustainable cronut, quinoa tumblr banjo palo santo shoreditch raw denim chicharrones yuccie. VHS pork belly taxidermy, schlitz pug tumblr art party cloud bread. Poke shoreditch letterpress retro affogato. Hot chicken heirloom kinfolk freegan. Hoodie gastropub next level williamsburg vice wolf cloud bread tattooed before they sold out, tote bag slow-carb scenester mixtape iPhone. Single-origin coffee raclette chillwave, cloud bread lumbersexual blue bottle fam keytar pickled crucifix.</p>
  <p>Cliche iceland tousled glossier banh mi hammock. Waistcoat man braid sustainable cronut, quinoa tumblr banjo palo santo shoreditch raw denim chicharrones yuccie. VHS pork belly taxidermy, schlitz pug tumblr art party cloud bread. Poke shoreditch letterpress retro affogato. Hot chicken heirloom kinfolk freegan. Hoodie gastropub next level williamsburg vice wolf cloud bread tattooed before they sold out, tote bag slow-carb scenester mixtape iPhone. Single-origin coffee raclette chillwave, cloud bread lumbersexual blue bottle fam keytar pickled crucifix.</p>
</div><!-- ROW 1 -->

</div><!-- CONTAINER -->

app/views/pages/users.html.erb
<h1>New Users Page</h1>

app/views/recipes/_form.html.erb
<div class="container">

<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %><!-- error loop-->

<div class="row">
  <div class="form-group">
    <h3>Add or Delete Image</h3>
    <%= form.file_field :image %>
    <% if @recipe.image? %>
      <%= image_tag @recipe.image.url, class: "recipe-show" %>
        <br>
        <br>
      <%= form.check_box :remove_image %>
        Remove Image
    <% end %><!-- image loop-->
  </div><!-- image form -->
</div><!-- image row -->

<div class="row">
  <div class="field">
    <h3>Add or Update Title</h3>
    <%= form.label :title %>
    <%= form.text_field :title, id: :recipe_title %>
  </div><!-- title form -->
</div><!-- title row -->

<div class="row">
  <div class="field">
    <h3>Add or Update Description</h3>
    <%= form.label :description %>
    <%= form.text_area :description, id: :recipe_description %>
  </div><!-- column form -->
</div><!-- description row -->

<div class="row">
  <div class="form-group">
    <h3>Add or Delete Ingredients</h3>
    <%= form.nested_fields_for :ingredients do |ingredient| %>
    <%= ingredient.text_field :content %>
    <%= ingredient.remove_nested_fields_link %>
    <% end %><!-- ingredients loop -->
    <%= form.add_nested_fields_link :ingredients %>
  </div><!-- ingredients form -->
</div><!-- ingredients row -->

<div class="row">
  <div class="form-group">
    <h3>Add or Delete Steps</h3>
    <%= form.nested_fields_for :steps do |step| %>
    <%= step.text_field :direction %>
    <%= step.remove_nested_fields_link %>
    <% end %><!-- steps loop -->
    <%= form.add_nested_fields_link :steps %>
  </div><!-- steps form -->
</div><!-- steps row -->  

<div class="row">
  <div class="actions">
    <h3>Create/Update Recipe</h3>
    <%= form.submit %>
  </div>
</div><!-- submit row -->

<% end %><!-- end of form -->

</div>

app/views/recipes/edit.html.erb
<div class="container">

<h1>Edit Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

</div>

app/views/recipes/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
  <h1>Tina's Recipe App</h1>
  <br>
   <%= link_to 'Click Here to Enter New Recipe', new_recipe_path %>
  </div>
  <div class="col-md-6">
    <p>Cliche iceland tousled glossier banh mi hammock. Waistcoat man braid sustainable cronut, quinoa tumblr banjo palo santo shoreditch raw denim chicharrones yuccie. VHS pork belly taxidermy, schlitz pug tumblr art party cloud bread. Poke shoreditch letterpress retro affogato. Hot chicken heirloom kinfolk freegan. Hoodie gastropub next level williamsburg vice wolf cloud bread tattooed before they sold out, tote bag slow-carb scenester mixtape iPhone. Single-origin coffee raclette chillwave, cloud bread lumbersexual blue bottle fam keytar pickled crucifix.</p>
  </div>
</div><!-- ROW 1 -->
<br>
<div class="row">
  <% @recipes.each do |recipe| %>
    <div class="col-md-4">
      <div class="recipe-box">
      <%if recipe.image? %>
      <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe%>
      <% end %>
      <ul>
        <li><%= recipe.title %></li>
        <li><%= recipe.description %></li>
        <li><%= link_to 'Show', recipe %> <% if user_signed_in? %>| <%= link_to 'Edit', edit_recipe_path(recipe) %> | <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %> </li>
      </ul>
      </div><!-- recipe box -->
    </div><!-- col-md-4 -->
  <% end %>
</div><!-- ROW 2 --> 

</div><!-- container -->

app/views/recipes/new.html.erb
<div class="container">

<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<br>
<%= link_to 'Back', recipes_path %>

</div><!-- CONTAINER -->

app/views/recipes/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

	<% if @recipe.image? %>
	<%= image_tag @recipe.image.url, class: "recipe-show" %>
	<% end %>

<br>
<br>

<div class="row">
<div class="col-md-3">
<h4>
  <strong>Title:</strong>
  <br>
  <%= @recipe.title %>
</h4>
</div>

<div class="col-md-3">
<h4>
  <strong>Description:</strong>
  <br>
  <%= @recipe.description %>
</h4>
</div>

<div class="col-md-3">
<h4>Ingredients</h4>
<ul>
	<% for @ingredient in @recipe.ingredients %>
		<li><%= @ingredient.content %></li>
	<% end %>
</ul>
</div>

<div class="col-md-3">
<h4>Steps</h4>
<ol>
	<% for @step in @recipe.steps %>
		<li><%= @step.direction %></li>
	<% end %>
</ol>
</div>

</div><!-- end row -->

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>
</div>